### PR TITLE
UpdatesWith

### PR DESCRIPTION
**Pull request by abakum**
# :speech_balloon: Description

[//]: # (Please include a summary of the change, if it was related to the issue specify it)

...

## :monocle_face: Type of change

[//]: # (Please select options that are relevant, and delete others)

- [+] New feature (non-breaking change which adds functionality)

# :clipboard: Checklist

[//]: # (Please make sure to check all tasks)

- [ ] My code follows the [style guidelines](../docs/CONTRIBUTING.md#art-style-guidelines) of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented on my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have added unit tests that prove my fix is effective or that my feature works
- [ ] Feature or fix that I was working on is in "[releasable](../docs/CONTRIBUTING.md#always-releasable)" state

### CODE REVIEW

**Comment by mymmrac** [comment]
This implementation is too specific, I don't think it's useful to include it as is + there are no tests for it.

Here are a couple of my suggestions:
- Convert this code into example
- Move it to separate repo as extension/utility for Telego (I can mention it in Telego's README if it will be useful)
- Add this code as utility in `telegoutil` + make it more generic + add tests (I can do this myself, but not sure when)

**Comment by mymmrac** [comment]
Added example of using Ngrok in most generic way, so this is not needed any more.

https://github.com/mymmrac/telego/blob/main/examples/ngrok/main.go

**Comment by abakum** [comment]
Or in some other way so that the setting secretToken in FastHTTPWebhookServer affects to the SetWebhookParams and vice versa

**Comment by mymmrac** [comment]
Hmm good point, I will think about this

**Comment by abakum** [comment]
@mymmrac Please look https://github.com/mymmrac/telego/commit/82b3921cacd4ce58ab8aa8cf0c9fd04f804ded73#r116974092

**Pull request closed without merging**
